CREATE DATABASE IF NOT EXISTS folio;
USE folio;
CREATE TABLE IF NOT EXISTS user (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    `fname` VARCHAR(32) NOT NULL,
    `lname` VARCHAR(32) NOT NULL,
    `email` VARCHAR(64) NOT NULL,
    `pwd` CHAR(32) NOT NULL,
    `status` TINYINT DEFAULT 1 NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);